# BUILD SETTINGS

url:            ''
baseurl:        ''
permalink:      pretty
theme:          iiifc-theme
source:         source

markdown:       kramdown
exclude:        [node_modules]
sass:
  style:        compressed
  sass_dir:     _sass

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-liquify

# URLS
root_url:       https://iiif.io
api_url:        https://iiif.io/api
guides_url:     https://guides.iiif.io

# THEME VARS
iiifc-theme:
  logo:       assets/images/logos/logo-sm.png
  acronym:    IIIF
  title:      International Image Interoperability Framework
  tagline:    "International Image Interoperability Framework: A community driven image framework with well defined APIs for making the world’s image repositories interoperable and accessible"
  email:      iiif-discuss@googlegroups.com
  block-start: "<div class='container-block is-max-widescreen'><div class='container' markdown='1'>"
  block-center-start: '<div class="container-block is-max-widescreen"><div class="container has-text-centered" markdown="1">'
  block-end: '</div></div>'
  navbar_menu:
    - label: 'Home'
      link: '{{ site.root_url }}'
    - label: 'Demos'
      link: '{{ site.root_url }}/demos'
    - label: 'News & Events'
      link: ''
    - label: 'Get Involved'
      link: '{{ site.root_url }}/get-involved'
      sub:
        - label: 'Community Groups'
          link: '{{ site.root_url }}/community/groups'
        - label: 'Consortium'
          link: '{{ site.root_url }}/community/consortium'
        - label: 'Join Newsletter'
          link: '{{ site.root_url }}/newsletter'
        - label: 'Contact Us'
          link: '{{ site.root_url }}/community/consortium/staff/'
    - label: 'Get Started'
      link: '{{ site.root_url }}/get-started'
      sub:
        - label: 'How IIIF Works'
          link: '{{ site.root_url }}/how-iiif-works'
        - label: 'APIs & Documentation'
          link: '{{ site.api_url }}'
        - label: 'Cookbooks'
          link: '{{ site.root_url }}/get-started/cookbook'
        - label: 'Training'
          link: '{{ site.root_url }}/get-started/training'
  footer_menu:
    - heading: About
      sub:
        - label: 'How IIIF Works'
          link:  '{{ site.root_url }}/how-iiif-works'
        - label: 'APIs & Documentation'
          link:  '{{ site.api_url }}'
        - label: 'Demos'
          link:  '{{ site.root_url }}/demos'
        - label: 'Tutorials'
          link:  '{{ site.guides_url }}'
    - heading: Stay Connected
      sub:
        - label: 'Events & News'
          link:  ''
        - label: 'Join Newsletter'
          link:  '{{ site.root_url }}/newsletter'
        - label: 'Community Groups'
          link:  '{{ site.root_url }}/community/groups'
        - label: 'Consortium'
          link:  '{{ site.root_url }}/community/consortium'
