url:            ''
baseurl:        /iiifc-theme
permalink:      pretty
source:         source
incremental:    true

exclude:
  - node_modules

collections:
  pages:
    output: true

organization:
  title:        IIIF | International Image Interoperability Framework
  tagline:      "International Image Interoperability Framework: A community driven image framework with well defined APIs for making the world’s image repositories interoperable and accessible"
  email:        iiif-discuss@googlegroups.com
  url:          //iiif.io
  logo:         assets/logo-sm.png
