# BUILD SETTINGS

url:            ''
baseurl:        ''
permalink:      pretty
theme:          udt-itf-theme
source:         source

markdown:       kramdown
exclude:        [node_modules]
sass:
  style:        compressed
  sass_dir:     _sass

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-liquify
  - jekyll-seo-tag

# THEME VARS
udt-itf-theme:
  logo:       assets/images/logos/logo-sm.png
  acronym:    UDT-ITF
  title:      Unlocking Digital Texts
  tagline:    "Towards an Interoperable Text Framework"
  email:      
  block-start: "<div class='container-block is-max-widescreen'><div class='container' markdown='1'>"
  block-center-start: '<div class="container-block is-max-widescreen"><div class="container has-text-centered" markdown="1">'
  block-end: '</div></div>'
  navbar_menu:
    - label: 'Home'
      link: '{{ site.root_url }}/'
    - label: "Project"
      link: '{{ site.root_url }}/project'
    - label: 'News & Events'
      link: '{{ site.root_url }}/news-and-events'
    - label: 'API'
      link: '{{ site.root_url }}/api'
  footer_menu:
    - heading: About
      sub:
        - label: 'What is UDT-ITF'
          link:  '{{ site.root_url }}'
        - label: 'API Documentation'
          link:  '{{ site.root_url }}/api'
    - heading: Stay Tuned
      sub:
        - label: 'News & Events'
          link:  '{{ site.root_url }}/news-and-events'
        - label: 'Contact Us'
          link:  '{{ site.root_url }}/contact'


# Jekyll SEO plugin info
tagline: "Unlocking Digital Texts - Towards an Interoperable Text Framework"
logo: /assets/favicon.ico
social:
  name: UDT-ITF
  links:
    - https://www.cdh.cam.ac.uk/research/projects/unlocking-digital-texts/

