url:          ''
baseurl:      ''
permalink:    'pretty'

exclude: ['*.gemspec', 'CODE_*', 'README*']

organization:
  title:        'IIIF | International Image Interoperability Framework'
  tagline:      'International Image Interoperability Framework: A community driven image framework with well defined APIs for making the world’s image repositories interoperable and accessible'
  email:        'iiif-discuss@googlegroups.com'
  url:          '//iiif.io'
  logo:         'assets/logo-sm.png'
