url:            ''
baseurl:        ''
permalink:      pretty
title:          "IIIF | International Image Interoperability Framework"

sass:
  style:        compressed
  sass_dir:     _sass

collections:
  pages:
    output: true

organization:
  acronym:      IIIF
  title:        International Image Interoperability Framework
  tagline:      "IIIF is an open standard for delivering high-quality, attributed digital objects online at scale. It’s also an international community developing and implementing the IIIF APIs. IIIF is stewarded by a consortium."
  email:        iiif-discuss@googlegroups.com
  url:          //iiif.io
  logo:         assets/images/logo-sm.png

navbar_menu:
  - label: 'Home'
    link: '/'
  - label: 'Demos'
    link: '/demos'
  - label: 'News & Events'
    link: '/news-and-events'
  - label: 'Get Involved'
    link: '/get-involved'
    sub:
      - label: 'Test Sub1'
        link: ''
  - label: 'Get Started'
    link: '/get-started'
    sub:
      - label: 'Test Sub2'
        link: ''
